### PR TITLE
Fix Datadog dashboard and monitor queries

### LINKED ISSUE #457: [Bug]: Datadog alerting issues for `DownloadGrantsGovDB` Lambda
### Why is this issue important?

**Note:** This issue is related to #456.

We rely on Datadog monitors and service health dashboards to keep us informed about service availability and reliability issues. However, this infrastructure did _not_ accurately alert us to the problem described in #456.

### Current State

- As of right now, the `DownloadGrantsGovDB` Lambda handler has been failing in both Production and Staging environments since Saturday, 2023-10-28. Although the primary cause of these failures has been identified (see #456), a secondary problem seems to be that these failures did not trigger alerting in any of our Datadog monitors, which are configured for both ([Staging](https://app.datadoghq.com/monitors/130337503) and [Production](https://app.datadoghq.com/monitors/131628179) environments) in Terraform.
- Relatedly, although our [service health dashboard](https://app.datadoghq.com/dashboard/rr7-pf5-sx6/grants-ingest-service-dashboard?refresh_mode=paused&from_ts=1698458845176&to_ts=1698882798118&live=false) does represent these failures, it also shows an equal number of successful invocations, which is obviously incorrect given that the Lambda itself is reporting invocations as failed. 
    - Note: The specific dashboard widget of concern is the "Invocation Status" widget, located in the "DownloadGrantsGovDB" group. (See screenshot below)
    - Screenshot: 
Invocation Status

### Expected State

1. When invocations to the `DownloadGrantsGovDB` handler have a nonzero error ratio for at least 10 hours, our Datadog monitor status changes to "Alert" for the relevant deployment environment.
2. Failed invocation counts do not appear alongside an equal number of successful invocation counts in the dashboard.

### Implementation Plan

1. Identify the reason why our Datadog monitors ([defined in Terraform](https://github.com/usdigitalresponse/grants-ingest/blob/dca5f3bce5640b4d14f912971d1547e3873c4d93/terraform/datadog_monitors.tf#L41-L65)) are failing to detect the problem. Presumably this is the result of a bad query implementation, so either:
    1. The query needs to be adjusted
    2. The query needs to be replaced outright in favor of a more effective strategy
2. Identify the reason why our Datadog dashboard (also [defined in Terraform](https://github.com/usdigitalresponse/grants-ingest/blob/dca5f3bce5640b4d14f912971d1547e3873c4d93/terraform/datadog_dashboard.tf#L236-L279)) is errantly reporting successful invocation counts.
3. Spot-check similar dashboard widgets to ensure they are not subject to the same problem, and fix as-needed.

### PR DESCRIPTION
**Pull request by TylerHendrickson**
## Description

This PR fixes a few issues that are causing some of our Datadog monitors and dashboards to miss important operational issues. This was first noticed because monitors failed to alert us about failures related to #456, which on closer inspection also revealed that Lambda invocation success rates were being incorrectly represented on the service dashboard in Datadog.

All in all, there are three distinct problems that this PR addresses:
1. **Problem:** Datadog monitors (`Grant modification events failed to publish` and `DownloadGrantsGovDB failed`) failed to alert, despite the presence of DLQ messages and failed Lambda invocations.
    - **Cause:** Datadog monitor queries are case-sensitive (which is unlike dashboard queries), and most AWS metrics are tagged with lowercase values. Because we configure the monitor queries by interpolating resource names (which are mixed-case) as selector values, selectors like `queuename:grants_ingest-PublishGrantEvents-dlq` and `functionname:grants_ingest-DownloadGrantsGovDB` were not matching their intended resources, causing the queries to yield zero-count results.
    - **Solution:** Ensure that AWS resource names/identifiers are lowercased when interpolated as selector values in monitor queries. b6f4aa13df3043cbd83960d0a8cce228240c0702
2. **Problem:** The per-Lambda "Invocation Status" widgets in our service dashboard were incorrectly showing successful invocation counts (alongside correct failure counts).
    - **Cause:** The raw total invocation counts were being incorrectly represented as "Succeeded" metrics. The Lambda integration for Datadog does not provide a discrete metric for successful invocation counts – `aws.lambda.invocations` only represents total invocations, while `aws.lambda.errors` represents failed invocations.
    - **Solution:** Update the "Succeeded" bar graph to be computed as `succeeded = total - failed`. 7023760b0d29c7f697e737f1a031b0f8f73686e0
3. **Problem:** The SQS DLQ widgets in the dashboard failed to represent the presence of dead-letter queue messages.
    - **Cause:** The queue name used as a selector in the query was improperly configured as an inadvertent result of #360.
    - **Solution:** Replace the (incorrect) hard-coded queue name in the dashboard query with the lowercased output value of `module.PublishGrantEvents.dlq_name`, which correctly identifies the SQS resource in Datadog. afc72475ee0a8ec7b6ef3b82f568673967bb96f1

Additionally, this PR updates all dashboard queries that were using hard-coded values for the `handlername:` (custom tag) selector to instead use the native `functionname:` provided by the Lambda integration. This is mostly a cleanup effort, but given the issues with hard-coding resource names described above, this seemed like a good impetus to make the change.

## Testing

_Note:_ A subset of these changes were manually tested on Datadog draft resources in order to confirm the issues and viability of their corresponding solutions.

1. Check the Terraform plan comment on this PR (which will be published by a CI job soon after the PR is opened) to ensure that the changes look correct.
2. Once this PR is merged to Staging, check the `(Draft - staging)` Datadog resources to confirm they are still working. Additionally, inspect historical data on the dasboard and monitors to confirm they are accurately representing the failure scenarios addressed by #458.

## Checklist
- [x] Provided ticket and description
- [x] Provided testing information
- [x] Provided adequate test coverage for all new code
- [x] Added PR reviewers

### CODE REVIEW

File: cmd/DownloadGrantsGovDB/handler.go [hunk 1]
```diff
@@ -23,7 +23,7 @@ type ScheduledEvent struct {
 // grantsURL returns the download URL for the Grants.gov database export.
 func (e *ScheduledEvent) grantsURL() string {
 	return fmt.Sprintf("%sGrantsDBExtract%sv2.zip",
-		env.GrantsGovBaseURL + env.GrantsGovPathURL,
+		env.GrantsGovBaseURL+env.GrantsGovPathURL,
```
Comment (TylerHendrickson) [inline cmd/DownloadGrantsGovDB/handler.go:26]: This change is nonfunctional; was applied automatically when I ran `task check` locally (which runs `go fmt`) before pushing.

Comment (SDBowen) [reply cmd/DownloadGrantsGovDB/handler.go:26]: Missed that part my last PR; thanks for pointing it out!

**Review by SDBowen — APPROVED** [review]
